package io.github.meistermods.siliconic.config;

import net.minecraftforge.common.ForgeConfigSpec;
import org.apache.commons.lang3.tuple.Pair;

/** Shared gameplay settings. Values that affect menus are synchronized through container data. */
public final class SiliconicConfig {
  public static final ForgeConfigSpec SPEC;
  public static final Values VALUES;

  static {
    Pair<Values, ForgeConfigSpec> configured = new ForgeConfigSpec.Builder().configure(Values::new);
    VALUES = configured.getLeft();
    SPEC = configured.getRight();
  }

  public static final class Values {
    public final ForgeConfigSpec.IntValue generatorOutputPerTick;
    public final ForgeConfigSpec.IntValue powerTransferPerConnection;
    public final ForgeConfigSpec.IntValue powerNetworkMaxCables;
    public final ForgeConfigSpec.IntValue powerNetworkCacheTicks;
    public final ForgeConfigSpec.IntValue powerBufferCapacity;
    public final ForgeConfigSpec.IntValue powerBufferOutputPerTick;
    public final ForgeConfigSpec.IntValue cleanroomEnergyPerTick;
    public final ForgeConfigSpec.IntValue cleanroomScanInterval;
    public final ForgeConfigSpec.IntValue cleanroomMaxVolume;
    public final ForgeConfigSpec.IntValue cleanroomMaxDistance;
    public final ForgeConfigSpec.IntValue cleanroomEntityContamination;
    public final ForgeConfigSpec.IntValue cleanroomSourceContamination;
    public final ForgeConfigSpec.IntValue logisticsMaxPipes;
    public final ForgeConfigSpec.IntValue logisticsScanInterval;
    public final ForgeConfigSpec.IntValue logisticsTransferInterval;
    public final ForgeConfigSpec.IntValue logisticsTransferLimit;
    public final ForgeConfigSpec.IntValue waferMutationsPerTick;

    private Values(ForgeConfigSpec.Builder builder) {
      builder.push("power");
      generatorOutputPerTick =
          builder
              .comment("Energy generated by the coal generator each tick.")
              .defineInRange("generatorOutputPerTick", 40, 1, 10_000);
      powerTransferPerConnection =
          builder
              .comment("Maximum energy offered to one receiver each tick.")
              .defineInRange("transferPerConnection", 200, 1, 1_000_000);
      powerNetworkMaxCables =
          builder
              .comment("Maximum cable positions scanned in one connected power network.")
              .defineInRange("maxCablesPerNetwork", 4_096, 64, 65_536);
      powerNetworkCacheTicks =
          builder
              .comment("Fallback interval for refreshing cached power-network topology.")
              .defineInRange("topologyCacheTicks", 100, 1, 1_200);
      powerBufferCapacity =
          builder
              .comment("Maximum energy stored by one energy buffer.")
              .defineInRange("bufferCapacity", 200_000, 1_000, 10_000_000);
      powerBufferOutputPerTick =
          builder
              .comment("Maximum total energy distributed by one energy buffer each tick.")
              .defineInRange("bufferOutputPerTick", 800, 1, 1_000_000);
      builder.pop();

      builder.push("cleanroom");
      cleanroomEnergyPerTick =
          builder
              .comment("Energy consumed by a powered conditioner each tick.")
              .defineInRange("energyPerTick", 40, 0, 10_000);
      cleanroomScanInterval =
          builder
              .comment("Ticks between room scans. Scans are staggered by conditioner position.")
              .defineInRange("scanInterval", 20, 5, 1_200);
      cleanroomMaxVolume =
          builder
              .comment("Maximum number of traversable positions in one cleanroom scan.")
              .defineInRange("maxVolume", 4_096, 64, 65_536);
      cleanroomMaxDistance =
          builder
              .comment("Maximum Chebyshev distance from a conditioner during room scans.")
              .defineInRange("maxDistance", 32, 4, 256);
      cleanroomEntityContamination =
          builder
              .comment("Cleanliness lost per unprotected entity during one scan.")
              .defineInRange("entityContaminationPerScan", 2, 0, 100);
      cleanroomSourceContamination =
          builder
              .comment("Cleanliness lost per equipment or block pollution source per scan.")
              .defineInRange("sourceContaminationPerScan", 4, 0, 100);
      builder.pop();

      builder.push("logistics");
      logisticsMaxPipes =
          builder
              .comment("Maximum pipe positions scanned by one logistics controller.")
              .defineInRange("maxPipesPerNetwork", 4_096, 64, 65_536);
      logisticsScanInterval =
          builder
              .comment("Ticks between staggered logistics-network refreshes.")
              .defineInRange("scanInterval", 40, 5, 1_200);
      logisticsTransferInterval =
          builder
              .comment("Ticks between logistics transfer attempts.")
              .defineInRange("transferInterval", 10, 1, 1_200);
      logisticsTransferLimit =
          builder
              .comment("Maximum items moved in one transfer attempt.")
              .defineInRange("transferLimit", 8, 1, 64);
      builder.pop();

      builder.push("waferEditor");
      waferMutationsPerTick =
          builder
              .comment("Maximum cell and pin edits accepted from one open menu per tick.")
              .defineInRange("mutationsPerTick", 16, 1, 128);
      builder.pop();
    }
  }

  private SiliconicConfig() {}
}
